### ISSUE TITLE
path error

### ISSUE THREAD

**Issue by cyberspar** [starcolon/photo-auto-balance#21]
FileNotFoundError: [Errno 2] No such file or directory: './data/raw//../../model.cnn0'

**Comment by tao-pr** [comment]
Hi, can you do me a favour by sharing the steps to reproduce?

**Comment by cyberspar** [comment]
thanks for your reply!

actually ,i'm just started to learn CNN and i wanted to reproduce your code. i have already installed all the necessary moduels ,but the version might not be the same as its written in the requirements.txt (i cant use your quick start command ,so i separately install the requirements in anaconda3.)But something wrong happened while Loading part #0 and i cant figure out why.

=====================
Loader started ...
=====================
Executing function...
Loading samples...
(2, 3, 240, 240)
Loading the models at ./data/raw//../../model.cnn
...Loading part #0
Traceback (most recent call last):

  File "<ipython-input-1-7bd5405ca847>", line 1, in <module>
    runfile('C:/Users/wo187/Desktop/photo-auto-balance-master/loader.py', wdir='C:/Users/wo187/Desktop/photo-auto-balance-master')

  File "C:\Users\wo187\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/wo187/Desktop/photo-auto-balance-master/loader.py", line 172, in <module>
    process_with(path, with_func)

  File "C:/Users/wo187/Desktop/photo-auto-balance-master/loader.py", line 162, in process_with
    return f(dataset)

  File "C:/Users/wo187/Desktop/photo-auto-balance-master/loader.py", line 142, in enhance
    model = load_model(path_model, np.shape(X[0]), 4) # TAOTOREVIEW: Find vector y size programmatically

  File "C:\Users\wo187\Desktop\photo-auto-balance-master\model\core.py", line 46, in load_model
    return CNN.load(path, image_dim, final_vec_dim)

  File "C:\Users\wo187\Desktop\photo-auto-balance-master\model\cnn.py", line 227, in load
    params = pickle.load(open(path + str(i), 'rb'))

FileNotFoundError: [Errno 2] No such file or directory: './data/raw//../../model.cnn0'

**Comment by tao-pr** [comment]
It is likely you started running the classification without having any models trained beforehand. Can you try preparing the trainset of images and run the training process? See the instruction from this bullet of README onwards:
https://github.com/starcolon/photo-auto-balance#prepare-training-directory

**Comment by cyberspar** [comment]
you mean i have to train all the images in the /data/raw first?So which .py  file should i  run  first?

**Comment by tao-pr** [comment]
yes, the repository itself does not include an initial model for you so you should train on your own. 

Basically a quick way of training a model is putting as many as images (low-resolution preferred, otherwise it is taking ages to finish) inside a directory and run the following 

```
$ python3 loader.py --train --limit 5000 --dir /path/to/trainset/
```

Disclaimer: The code is not very efficient so you may encounter a very slow and sluggish training process. That is expected and I am aware of it. Ideally you need lots of images to train so it surely take days.

**Comment by cyberspar** [comment]
but how can i run this command in windows cmd?sorry i'm a newbie.

**Comment by tao-pr** [comment]
yes. you can `cd` into the directory where you clone the project into and execute it. the script just executes the `loader.py` script of the project, nothing specific to the OS.

**Comment by mecury1** [comment]
so i run this command in cmd ,but still can't load photos .
C:\Users\wo187\Desktop\photo-auto-balance-master>python loader.py --train --limit 30 --dir C:\Users\wo187\Desktop\photo-auto-balance-master\trainset\raw
C:\Users\wo187\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
[35m=====================[0m
[35mLoader started ...[0m
[35m=====================[0m
Executing function...
[36mProcessing ... [0m 1519711429_リリ2.jpg
...[32m5[0m filters applied
[33m...Saving outputs[0m
Traceback (most recent call last):
  File "loader.py", line 172, in <module>
    process_with(path, with_func)
  File "loader.py", line 162, in process_with
    return f(dataset)
  File "loader.py", line 64, in train
    .save('{0}/{1}-{2:02d}.jpg'.format(dir_out,name,i))
  File "C:\Users\wo187\Anaconda3\lib\site-packages\PIL\Image.py", line 1932, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\wo187\\Desktop\\photo-auto-balance-master\\trainset\\raw../out/1519711429_リリ2-00.jpg'

**Comment by cyberspar** [comment]
i run this command in cmd,but still cant load the photos .wonder if i set the wrong directory or put the wrong photos .

C:\Users\wo187\Desktop\photo-auto-balance-master>python loader.py --train --limit 30 --dir C:\Users\wo187\Desktop\photo-auto-balance-master\trainset\raw
C:\Users\wo187\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
[35m=====================[0m
[35mLoader started ...[0m
[35m=====================[0m
Executing function...
[36mProcessing ... [0m 1519711429_リリ2.jpg
...[32m5[0m filters applied
[33m...Saving outputs[0m
Traceback (most recent call last):
  File "loader.py", line 172, in <module>
    process_with(path, with_func)
  File "loader.py", line 162, in process_with
    return f(dataset)
  File "loader.py", line 64, in train
    .save('{0}/{1}-{2:02d}.jpg'.format(dir_out,name,i))
  File "C:\Users\wo187\Anaconda3\lib\site-packages\PIL\Image.py", line 1932, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\wo187\\Desktop\\photo-auto-balance-master\\trainset\\raw../out/1519711429_リリ2-00.jpg'

**Comment by tao-pr** [comment]
You may want to create a directory for an output if you haven't. From your case it is supposed to be `C:\Users\wo187\Desktop\photo-auto-balance-master\trainset\out`

The script itself doesn't create an output directory for you.  The script has to have it to store the generated trainset from your input images.Then you can try again

**Comment by cyberspar** [comment]
actually i have already created \trainset\out and \trainset\raw and \trainset\unflitered,all in the \trainset directory ,just like you wrote in the readme file. And set "out" and "unflitered" empty,also put 30 .jpg  picture in the "raw" file.

**Comment by tao-pr** [comment]
quick question. did you see any files written by the script to the "out" directory? i'm wondering if it fails in the middle or otherwise

btw, the command you ran above just looks fine to me.

**Comment by cyberspar** [comment]
There is a trainset.scv file in the \trainset directory,but it doesn't contain any data in it.still cant load the picture in the raw file.

**Comment by tao-pr** [comment]
My assumption based on the given log file above is your images may contain non-unicode characters in their file names. Can you try with english-only file names?

If this doesn't solve the issue, I would doubt if the Anaconda environment has a permission to write the output data into your output dir.

**Comment by cyberspar** [comment]
its all english-only file names ,so i wonder if its something wrong with anaconda environments .but i run the 'python loader.py'command in cmd,not anaconda ,so it might be hard to find the problems at anaconda environment .(but at first i run the loader.py at spyder,under anaconda environment.)

**Comment by tao-pr** [comment]
I'm convinced I know why now. I honestly overlooked some small details ...

You're running on Windows and it can't find the "constructed" path as you see from the error message saying "C:\Users\wo187\Desktop\photo-auto-balance-master\trainset\raw../out/1519711429_リリ2-00.jpg" ...

Did you notice the forward slashes there? 
It's obviously not gonna work on Windows by all means.

So, in your case you may want to make some changes to `loader.py`. There are lots of path variables being constructed with '/'.

for example

```python
  print(colored('Processing ... ','cyan'), s)
  src     = load_img(args['dir'] + '/' + s)
  dir_out = args['dir'] + '../out
```

should change to:

```python
  print(colored('Processing ... ','cyan'), s)
  src     = load_img(args['dir'] + '\\' + s)
  dir_out = args['dir'] + '..\\out
```

And so on. Please note that it has to be double backslashes to escape into a single backslash when it interprets the string.

Good luck! I hope this could help

**Comment by cyberspar** [comment]
thank you so much for your reply! its a real big problem that i have ignored all the time .
i put 700 pictures in the raw file and start the training ,it successfully flitered 700 images and output 3500 images in the \trainset\out file and the trainset.csv has 3500 datas in it  ,but at the reading samples stage ,it stucks. after several minutes ,my computer restart itself !!!,
i wonder if 700 images is to much for my computer,so what should i do next?restart the --train again or just run the loader.py?

**Comment by tao-pr** [comment]
700 images are not a big number but you have to keep in mind that:
- Avoid using the large image, i would suggest using the images of low resolution of 300 px at most. The algorithm I implemented is not very efficient for large resolution.
- It's impossible to run the whole 700 images for training. Here is how the `--batch` argument comes into play. Try specifying a small number of batch and try out. It really depends on your system how much it can handle. Take a look at the file https://github.com/starcolon/photo-auto-balance/blob/master/train so you see the example usage of batch.

**Comment by mecury1** [comment]
thanks a lot .i will give another try.

**Comment by cyberspar** [comment]
As i put several picture in the \dataset\raw and set the command as "python loader.py --train --limit 700 --batch 150 --dir C:\Users\wo187\Desktop\photo-auto-balance-master\trainset\raw\" it started running .after 700 outputs were saved , it prints:
limit reached 
training started...
...700 raw images processed
...3500 samples to go
...2800 for training
...700 for validation
..reading samples

after restarted my computer several time ,it finally read the sample and start to create the cnn then it print down_sample not found.

**Comment by tao-pr** [comment]
looks like version disparity to me. 
did you install the python packages by the requirement.txt?

```
pip install -r requirements.txt
```

**Comment by cyberspar** [comment]
i limit the training number to 100 in order to prevent my computer from restarting,and after the training complete,it print this :
?[36mCreating a new CNN.?[0m
?[32mTraining started.?[0m
C:\Users\wo187\Anaconda3\lib\site-packages\lasagne\layers\conv.py:489: UserWarning: The `image_shape` keyword argument to `tensor.nnet.conv2d` is deprecated,
it has been renamed to `input_shape`.
  border_mode=border_mode)
Traceback (most recent call last):
  File "loader.py", line 172, in <module>
    process_with(path, with_func)
  File "loader.py", line 162, in process_with
    return f(dataset)
  File "loader.py", line 119, in train
    args['batch'])
  File "C:\Users\wo187\Desktop\photo-auto-balance-master\model\core.py", line 37, in train_model
    cnn.train(X, y, X_, y_, batch_size, epoch)
  File "C:\Users\wo187\Desktop\photo-auto-balance-master\model\cnn.py", line 71, in train
    output  = [layers.get_output(n) for n in self.nets] # Actual output
  File "C:\Users\wo187\Desktop\photo-auto-balance-master\model\cnn.py", line 71, in <listcomp>
    output  = [layers.get_output(n) for n in self.nets] # Actual output
  File "C:\Users\wo187\Anaconda3\lib\site-packages\lasagne\layers\helper.py", line 185, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "C:\Users\wo187\Anaconda3\lib\site-packages\lasagne\layers\pool.py", line 235, in get_output_for
    pooled = downsample.max_pool_2d(input,
NameError: name 'downsample' is not defined

when i use the import command to exam the requirements modules, all the import command goes well,only i have to change import pillow to import PIL.

**Comment by tao-pr** [comment]
very likely your pillow package is running on a different version than the code expects.
